const mongoose = require('mongoose');

const tokenQuestionSchema = new mongoose.Schema({
    pairName: String,
    Q1: String,
    Q1A: String,
    Q1B: String,
    Q1C: String,
    Q1D: String,
    Q1Answer: String,
    Q2: String,
    Q2A: String,
    Q2B: String,
    Q2C: String,
    Q2D: String,
    Q2Answer: String,
    Q3: String,
    Q3A: String,
    Q3B: String,
    Q3C: String,
    Q3D: String,
    Q3Answer: String,
    Q4: String,
    Q4A: String,
    Q4B: String,
    Q4C: String,
    Q4D: String,
    Q4Answer: String,
    Q5: String,
    Q5A: String,
    Q5B: String,
    Q5C: String,
    Q5D: String,
    Q5Answer: String,
})

module.exports = mongoose.model("TokensQuestion",tokenQuestionSchema)